apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: golang
  namespace: golang
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`golang.example.com`)
      kind: Rule
      services:
        - name: golang
          port: 80
  tls:
    secretName: golang-tls
