apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  labels:
    app: nodejs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      serviceAccountName: private
      containers:
        - name: nodejs
          image: egyhaty/dockerhub:node
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
