{{- $certificate := (index .Values "certificate") | default dict -}}
{{- if (index $certificate "enabled" | default false) -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ index $certificate "name" | quote }}
  labels:
    {{- include "charts.labels" . | nindent 4 }}
spec:
  secretName: {{ index $certificate "secretName" | quote }}
  issuerRef:
    name: {{ index (index $certificate "issuerRef" | default dict) "name" | quote }}
    kind: {{ index (index $certificate "issuerRef" | default dict) "kind" | default "ClusterIssuer" | quote }}
  dnsNames:
    {{- toYaml (index $certificate "dnsNames" | default list) | nindent 4 }}
{{- end }}