{{- $certificate := .Values.certificate | default dict -}}
{{- if ($certificate.enabled | default false) -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $certificate.name | quote }}
  labels:
    {{- include "charts.labels" . | nindent 4 }}
spec:
  secretName: {{ $certificate.secretName | quote }}
  issuerRef:
    name: {{ $certificate.issuerRef.name | quote }}
    kind: {{ $certificate.issuerRef.kind | default "ClusterIssuer" | quote }}
  dnsNames:
    {{- toYaml ($certificate.dnsNames | default list) | nindent 4 }}
{{- end }}