---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAlMQsa1fnPUp2rYy725EUvYFaieMVAEHOWNJ+i9ij3lrDl+LUA3FpDo1koppDkKWKPrs80ibgJM3yHQEe6+mNnIVUnNHPdG1HbGEUCrY783jKfPlWSxQ6qBYVtfpl6io60Z5tSgYFyZK8GbS2+i89y0Qzjym6wYdxglz6ngh5NUp5ToWG7bZ8A9F/8HzjF+8w95Ux/KndhLaZrRYcIf223+jHVgcfSTfUDqA0CQmHxl9yvNHy/N5DHaETxOiMivpg9uISSdJevKfWH9rMOjfwhjTnECT1JffWOTxp+WxqP8sPG5+Xn0fUwJMWysvkItzNF9rmzN2YEKxFWC8AOm3obzVnSS1wcjukH5/h5hQi1O4Z9mPFlPpD+8i+tViDsgBDZOua6MrEMsei22Rsl6FKST78Z7yxu5cZkblXWI7Y1FGjGAKHIsMxYBTG+QeIEpv5PhfRhb5n0wrAhqzUJDK3cA5TaNbwSh2ULh1gQxGeyOSYpszU3f4UKHsBT8QDiRlWFU+kcZ5I/DCNeh7UaSCzU1ErAoTHpz1+utk2JtCJ/PbisFADMdczmHlf0OLRqa49KmO1EIq2Lb2Bq0l1Ciz35wypSv6th6HMWbsCRXhS/g6N0mQR9yfruBynUU+wWbTLzkWXUvq2FMndkg/hzsz12KS82NbO4KtMfn16r/qI4s7b/UAgl7gZxK6vbl9CTTM0Rbdjob62J3xK5pg==
    admin-user: AgA16r7nF8rEippGpDnS3fbIEkThTj71zq3Z+l77arbr9ngUiCbzMlTHJiB9zMKdSB5mvAx8fk1pvjlw5bJMqQfumFccunVJKvB4xb6bx9a0d8PvRD7nHz5Iy/CRNi1R5MRbVPuSvG2oAJiWT7SOP5SNkpNXW9WGbPig71VtieIEAUEfmShKh8lkxo/Be/ffsL34Aj1oBGFs7R12NV3E9//3IRhQ+jzDbpEPvcFBZVwzmKfPjIjA9yeAUflqMOninra3Ow2jjdHgi1/aXjzXBLmZqL5oGy0O5wdBpKy2ge7qnAZWks603elRPNDmYSrBsSmVVZpfLKDdNKZWVL3F1N2/Ul4OEkL2Qk0+JftbTGLPfzvx9rQMa/rKKmWRTguvuxRbKInLQRYrWSr/iDZ13fFa06nGu74sy725LsIJ/tMBFKk2QbQkCtyYwoP3tyBv4VwOuwTPRbT0tLktE206cggpUPlW0gZ+A+HOqhR3YQ5Rt26xKjMjjSJ5HW8/aslqCbPGvLN3naKeDbzOT+39dy3iGd6eBMp1oHCnsCyqtogiFo2jO7H3vYlVXOK/zOCb9FNIZeujDZiLvgN5SvuYZcghAI0b+1saFEONno1/L/w+19OACVp3dwdafuttBPXjs2tUfoCzlaVpiwXwi80ViZ7F8wgB1hwUYS0igH6BDjLQRkCBsCVMlQSmh6SfgrYfqbjqcp4eGA==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque
