config:
  app: golang

replicaCount: 3

image:
  repository: egyhaty/golang
  tag: "sha-890ea19"
  pullPolicy: IfNotPresent

service:
  targetPort: 8080

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 128Mi

ingress:
  enabled: true
  className: traefik
  hosts:
    - host: go.murabba.net
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: go-murabba-net-tls
      hosts:
        - go.murabba.net

certificate:
  enabled: true
  name: go-murabba-net
  secretName: go-murabba-net-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - go.murabba.net

pdb:
  enabled: true
  minAvailable: 2

serviceMonitor:
  enabled: true
  labels:
    release: monitoring
  path: /metrics
  interval: 30s
