replicaCount: 2

image:
  repository: egyhaty/nodejs
  tag: "sha-ce6d46b"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: traefik
  host: node.karm.local
  path: /

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  NODE_ENV: production

probes:
  liveness:
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 10
  readiness:
    path: /ready
    initialDelaySeconds: 5
    periodSeconds: 5

certificate:
  enabled: true
  name: node-murabba-net
  secretName: node-murabba-net-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - node.murabba.net
