config:
  app: golang

replicaCount: 3

image:
  repository: egyhaty/golang
  tag: "sha-53b16d1"
  pullPolicy: IfNotPresent

service:
  targetPort: 8080

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 128Mi

ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: go.murabba.net
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: go-murabba-net-tls
      hosts:
        - go.murabba.net
