apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: services-applicationset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: nodejs
            valuesFile: values-node.yaml
          - name: golang
            valuesFile: values-go.yaml

  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default

      source:
        repoURL: https://github.com/EmaLinuxawy/karm-devops.git
        targetRevision: main
        path: charts
        helm:
          releaseName: '{{name}}'
          valueFiles:
            - values.yaml
            - '{{valuesFile}}'

      destination:
        server: https://kubernetes.default.svc
        namespace: default

      syncPolicy:
        automated:
          prune: true
          selfHeal: true