apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-murabba-net
  namespace: argocd
spec:
  secretName: argocd-murabba-net-tls
  dnsNames:
    - argocd.murabba.net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer