apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/EmaLinuxawy/karm-devops.git
    targetRevision: main
    path: nodejs/k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: my-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
