apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-resources
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/part-of: app-of-apps
spec:
  project: default
  source:
    repoURL: https://github.com/egyhaty/karm-devops
    targetRevision: main
    path: monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
